{% set version = "4.6.0" %}

package:
  name: qtconsole
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtconsole/qtconsole-{{ version }}.tar.gz
  sha256: 654f423662e7dfe6a9b26fac8ec76aedcf742c339909ac49f1f0c1a1b744bcd1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main
  skip: True  # [ppc64le]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyqt
    - traitlets
    - ipython_genutils
    - jupyter_core
    - jupyter_client >=4.1
    - pygments
    - ipykernel >=4.1  # not a real dependency, but require the reference kernel

test:
  commands:
    - jupyter qtconsole --help                                              # [win]
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'  # [linux]

  imports:
    - qtconsole
    - qtconsole.tests

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Jupyter Qt console
  description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich
    media output, session export, and more. The Qt console is a very
    lightweight application that largely feels like a terminal, but provides
    a number of enhancements only possible in a GUI, such as inline figures,
    proper multiline editing with syntax highlighting, graphical calltips, and
    more.
  doc_url: https://qtconsole.readthedocs.org/en/stable/
  dev_url: https://github.com/jupyter/qtconsole
  doc_source_url: https://github.com/jupyter/qtconsole/tree/master/docs

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
