{% set name = "qtconsole" %}
{% set version = "5.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qtconsole-{{ version }}.tar.gz
  sha256: 0d33371ce9ef554c7022ee300564ba9ffbd615e304ee615f6769d4068e063171

build:
  number: 0
  # Not available on s390x, ppc64le due to missing qt.
  skip: true  # [py<39 or ppc64le or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - ipykernel >=4.1
    - jupyter_core
    - jupyter_client >=4.1
    - pygments
    # The Qt console requires Qt, such as PyQt6, PySide6, PyQt5, PySide2.
    # Drop pyqt in run: avoids constraining environments that use PySide6/PyQt6
    # - pyqt
    - qtpy >=2.4.0
    - traitlets !=5.2.1,!=5.2.2
    - packaging
    - ipython_pygments_lexers

app:
  entry: jupyter-qtconsole
  summary: Jupyter Qt Console
  type: desk

test:
  imports:
    - qtconsole
    - qtconsole.tests
    - qtconsole.ansi_code_processor
    - qtconsole.base_frontend_mixin
    - qtconsole.client
    - qtconsole.completion_widget
    - qtconsole.console_widget
    - qtconsole.frontend_widget
    - qtconsole.inprocess
    - qtconsole.jupyter_widget
    - qtconsole.kill_ring
    - qtconsole.mainwindow
    - qtconsole.manager
    - qtconsole.qstringhelpers
    - qtconsole.qtconsoleapp
    - qtconsole.rich_jupyter_widget
    - qtconsole.rich_text
    - qtconsole.styles
    - qtconsole.svg
    - qtconsole.usage
    - qtconsole.util
  requires:
    - pip
    - pytest
    - flaky
    # pyqt 6 fails on linux CI with:
    # ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
    # tested locally, works fine
    - pyqt ==5.*
    - pytest-qt
    - pytest-asyncio
    - pytest-timeout
  source_files:
    - qtconsole/tests
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # 2022/8/1: Could not find the Qt platform plugin "xcb" in ""
    # This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
    # Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl.
    # - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'
    - jupyter qtconsole --help  # [win or osx]
    # Setup timeout
    # QT witout GUI
    # All these need for preventing freezing during pipeline build
    - set "QT_QPA_PLATFORM=offscreen"                  # [win]
    - export QT_QPA_PLATFORM=offscreen                 # [unix]
    - pytest -v qtconsole/tests -ra --timeout=300 --timeout-method=thread -k "not slow and not (test_scroll or test_input or test_debug or test_restart or test_link_handling)"

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Qt console
  description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich
    media output, session export, and more. The Qt console is a very
    lightweight application that largely feels like a terminal, but provides
    a number of enhancements only possible in a GUI, such as inline figures,
    proper multiline editing with syntax highlighting, graphical calltips, and
    more.
  doc_url: https://qtconsole.readthedocs.io
  dev_url: https://github.com/jupyter/qtconsole

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
