{% set version = "4.4.1" %}

package:
  name: qtconsole
  version: {{ version }}

source:
  fn: qtconsole-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qtconsole/qtconsole-{{ version }}.tar.gz
  sha256: 7870b19e6a6b0ab3acc09ee65463c0ca7568b3a01a6902d7c4e1ed2c4fc4e176

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - ipykernel >=4.1
    - jupyter_client >=4.1
    - jupyter_core
    - pygments
    - pyqt
    - traitlets

  run:
    - python
    - ipykernel >=4.1
    - jupyter_client >=4.1
    - jupyter_core
    - pygments
    - pyqt
    - traitlets

test:
  commands:
    - jupyter qtconsole --help                                              # [not linux]
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'  # [linux]

  imports:
    - qtconsole
    - qtconsole.tests

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Jupyter Qt console

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
