{% set name = "qtconsole" %}
{% set version = "5.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qtconsole-{{ version }}.tar.gz
  sha256: 8f9db97b27782184efd0a0f2d57ea3bd852d053747a2e442a9011329c082976d

build:
  noarch: python
  number: 0
  # Not available on s390x, ppc64le due to missing qt.
  skip: true  # [s390x or ppc64le]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.6
    - ipykernel >=4.1  # not a real dependency, but require the reference kernel
    - ipython_genutils
    - jupyter_client >=4.1
    - jupyter_core
    - pygments
    - pyqt
    - pyzmq >=17.1
    - qtpy
    - traitlets

app:
  entry: jupyter-qtconsole
  summary: Jupyter Qt Console
  type: desk

test:
  imports:
    - qtconsole
    - qtconsole.tests
  requires:
    - pip
    - python <3.10
  commands:
    - pip check
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help' # [not ((linux and aarch64) or osx)]

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Qt console
  description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich
    media output, session export, and more. The Qt console is a very
    lightweight application that largely feels like a terminal, but provides
    a number of enhancements only possible in a GUI, such as inline figures,
    proper multiline editing with syntax highlighting, graphical calltips, and
    more.
  doc_url: https://qtconsole.readthedocs.org/en/stable/
  dev_url: https://github.com/jupyter/qtconsole
  doc_source_url: https://github.com/jupyter/qtconsole/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
