{% set version = "5.2.2" %}

package:
  name: qtconsole
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtconsole/qtconsole-{{ version }}.tar.gz
  sha256: 8f9db97b27782184efd0a0f2d57ea3bd852d053747a2e442a9011329c082976d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main
  skip: true  # [s390x or ppc64le]

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.6
    - pyqt
    - traitlets
    - ipython_genutils
    - jupyter_core
    - jupyter_client >=4.1
    - pygments
    - ipykernel >=4.1  # not a real dependency, but require the reference kernel
    - qtpy
    - pyzmq >=17.1

app:
  entry: jupyter-qtconsole
  summary: Jupyter Qt Console
  type: desk

test:
  requires:
    - pip

  commands:
    - pip check
    - jupyter qtconsole --help                                              # [win]
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'  # [linux and not aarch64]

  imports:
    - qtconsole
    - qtconsole.tests

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Qt console
  description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich
    media output, session export, and more. The Qt console is a very
    lightweight application that largely feels like a terminal, but provides
    a number of enhancements only possible in a GUI, such as inline figures,
    proper multiline editing with syntax highlighting, graphical calltips, and
    more.
  doc_url: https://qtconsole.readthedocs.org/en/stable/
  dev_url: https://github.com/jupyter/qtconsole
  doc_source_url: https://github.com/jupyter/qtconsole/tree/master/docs

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
