{% set version = "4.2.1" %}

package:
  name: qtconsole
  version: {{ version }}

source:
  fn: qtconsole-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qtconsole/qtconsole-{{ version }}.tar.gz
  sha256: 25ec7d345528b3e8f3c91be349dd3c699755f206dc4b6ec668e2e5dd60ea18ef

build:
  number: 2
  script: python setup.py install

requirements:
  build:
    - python
    - ipykernel >=4.1
    - jupyter_client >=4.1
    - jupyter_core
    - pygments
    - pyqt 5.6.*
    - traitlets

  run:
    - python
    - ipykernel >=4.1
    - jupyter_client >=4.1
    - jupyter_core
    - pygments
    - pyqt 5.6.*
    - traitlets

test:
  commands:
    - jupyter qtconsole --help                                              # [not linux]
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'  # [linux]

  imports:
    - qtconsole
    - qtconsole.tests

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  license_file: COPYING.md
  summary: Jupyter Qt console

extra:
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - takluyver
    - ocefpaf
