travis:
  secure:
    BINSTAR_TOKEN: fp60W5hSpP3665WOi2AKeaV7kPCRy1rkBzKwE55IwDNeiqH2kroYOp78q88leOd8tosRoxowddjlUhEv1+Yrh8FlOtHLMtzL/hvtmdTHhRTi0SDrKTceqmZvjl8XccZg/T6AOJlTZvpkBcNFiczK88M25BBUf7Kwzyz42pQBU4VyEAFwXY15pYEAkWaS4/Y6VKgF5SIyDY6G0lCeMJrJRiAk08UXdVc8yuqVoVkILSoyOdSnHRwL+qU9rIWZxQyStzbu+VbFHuxfyqpOohZ8h2kBTnwhDeD736kkMe1h895G9tvpZLq5j9xyLcYKbFklNLMC7SY7WzLLuzqn0MWCbladPegGLxU5Jo57JWS/TFTauvmou8myvaKFSEr4O9FRBiqjxPV8rEpbjtJmj4bI3cb4NQ8ZpARiXdlRtfVQSrHgoP/6hJWEPisO971w1ATNvOFYBw76g0nIceoLbw/EEz6W1EPHVZJ+u4/bR/vpfHApEK20feczOi6Vd7FjqxNslh9rtt9Sq2U7dSXVFPKfy/90C+Turju+mFUIQkDTJjUoVyiDqZgF5pOeWRdIqbawjMXV3VjWUv6VLgwadW9VRvxjm0VbmedSKCNFdJ7iZskzpNzVF/rPPC0lPlfMRD6zhq5sePQtIhq6sO0lsMlHz4xUTHKNzFCrzsofo6I3e+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
