travis:
  secure:
    BINSTAR_TOKEN: fFTYwrQyFI2db1V5Ypmq6A7qa7fQJPd2uDSAYXvY+NE5FFYEgd48Q0nlZvLhosJaTJCWEpYdv4swZmQjAp/aj8Con22myusjYuWkt9yELXBYl+TetgD+/apa+t4rTqsNTIxz2ylpUvrZJWD7PtCeQ2RPBs2xObjZT+B6TaaGM8U344+8U3z37jIObiesSpmAPsamuqLtn2ldgKqgZL1/FdEML9YD5azglYvaFttcEibqyIE244y6DewHRFFrjrSj5s9wGgCrZMYWzsi34I8sKX9BaYqJTkBzmGbeTW6GooWXnGTJwxqLAg9Xu7CYviJPgi8WIeg7KUwB+52gW9BqFG3YcAWbuJ+J+wP7QEr16RcVbc0Cj4sIKu5rsZzE5oHNemvjgyLO/bwu9VSzPATIMgXJx9IIwr5AKDwtR0rjmJRXf+wIEyD5CdSpC92s0BQU1qrmomS7+tIQWIeESas6elXdaX8w/oSDJwRvY0izVq4PipcALj/EYLGaZemA3cuAOcreyfh0yaRgXBoWPbXzV/f9Dy+nLfsvYqVFliVE14UlKTcVdBxfNMr1uYx4jHglIV80r7JlvzifjTPXbbwBKU6eEd/iJdJirI0c9LjnUbg50HhJWqO+txqR3MOtLX1TH1fYrBp6m3VCuhLo8MswHULT9VniR2wZM+dea57DMrs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
