travis:
  secure:
    BINSTAR_TOKEN: 0oS5PeIzEc2DFtHUafhEWYvNCQ7/gRxU+//RYmtdDdXVmxMxZwNOHVyAvY77Sxd5nB+M5SxUvWsipfeXFgYd2+RoFpopzKSwu7tL2XnFFoCzq/gLYBG7lw6pa+FKsGAjM1BeAFxRM3NuEzSslnKetiaIXo0qurCcdD/3VLGy5ZEZmEE85U1V5VBtmB1SoQof+q15SPnn0LYPk+s+a6ZHKJoEpnZMzpZcCSy/gQ9ifMZXWI8JgWh0EIWIcSFvizIlVEOnc+AhR4D48wn1Ej3Hc/QzRsB9pt9c1/YUvEXPOET47FUpzUxZ61T2bckXZBT2+xIfFJSxU1eLQOl6bPyxS4omaGOxdwyuwDdU2CHks9pl5B0LsbTy48iPDPlwaHX/G4Bpj/8MBM1ONIr1s2zd3lP0lGRiy4wAVMHRCnAeNG92J6M1YMIg9sga6lcNTheRZX4CRMXeDIZ3xy0FmmQwq2LFxysz0CMOdH+Fk87mHsgCFpp1AmiuYLtB0Y26jcKGlT3hufZjmlrh7iHWmo8YKOlg3guvFB3aB7AmuT+JJ4H4cuTqD4ysHJmRBUk/p9cjxf9XDeKxdIwOUSS1UiTYLRjLEPkmxMVrPFrWirnoySQQt9SMjmFurljL9LsBgA3+Bz3IUiH74g1qPEgP1wjh1tvnFYvZEXuuzLmejX41ftc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
