travis:
  secure:
    BINSTAR_TOKEN: JsPTJsbTiiVkdComWFg2qKGHKl9OzRfGs+uibv7x1PFJYGAkKNRd49uItpOnQD5Qj0kF9s1dgyIyQjjvjgQc2/y4sIX8sB45eIC7opvJ8RVrmzRMnhLvL8DPz7rV+T8eIMWOvD/TN1GsaIMkW4IBZGwd4pu0wKcmbVkhoV2n4uV57YHHNoTUh/g47GlWXxC/Vn3MriwTcDhsxV30/VjdxH4FJuB2dCUjIykvZJY3zWzvYVLfKh4Rokh/UO5Uti2VKDS0Z+0acGm6yLGuGJvBVJccdJi15R/i2mTjED8D2aiJ9doKovXNYfAg3uEYMP4LTfFtnLTNE7IRflF4uwHd+O3IvEbfaGQSJI+mnvAom+KnShUFzIyZEpGBSPrIyyugdkQkgh/kS4NK2o+rWEyNOU45VabqhXiGbzvz9HWE1qtoegwn8ZTLI6emyUMTP/qpBnglqWPFzfZj/5q6vEB0bn0k6Ha/Y6EI5zuZQvLhCUIEvhWL2HgWT5/UxwgVCJ/GTdRNAxV3Cd9v6rxrzIOLyzHZnUbgdCQe9+PCcm6W4vYMa/FYGvQiDuTigi7Ask+9o/80QxCnhPChxej7wYIHF0sOr8LSH9m3GG/Xjns3Fvkmm6mpULxB31Wbco05bgXwKDOB5Xg21xKuAOtSsl3gifW1FCdtfDAphxQ343rrSx0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
