travis:
  secure:
    BINSTAR_TOKEN: LbP+JtiJ/PamiLK6pOoA2YOvTxUOB7I+a5sfAa4P35a2+HzLMjZXkEgU1iqknNaTmBdZGGOukXduZDrRXyAw2RjPBTF9SrIkGPgEWi3UScs4/lyzImG/WrwXDFWxZWjJzw+xkeLO77tW7vCGiTGc3yiuvlXzHazV+xfSXxXM1STbGp9eLz4KnrbUzGP8dkzP0LCuu04rFjPMW7OjGaME5CePJqKX6zmke4MqF6BZDMies0dqkfyV8gRg7nSNs2HABp8e7jlBD2YPi2eq07SjkMUrBV0/vv7H9anGOKdh9S39SfBqoWIaVToa1ZF0Kb0YMLbWowlR7Aw3VCvk0UzLXrFJwbGTYdYfxFxxXj3ElqUbYw/MNe8ffb44Z9BNWHjRp82u7LZOqWjx4bFyXMSTfWxlNZU6InsyUjuLnk5SgYKNT4PiqSYDC7wQbrm0gHdi4CgViUjZTX4k2bpq6XNSXqZbrsHDaeKznWPLG5vPDRMthgM96CzeTYr9IR9vlcgHBFGXifUKKUg8zQ/Edg8iafqnS5Nu9D/S42M6BSMkcx3gR9oxzxOAknDA6OLIrMn96OS4zs0W99wH7dXWLR/JMI1oTsFBIcDv3uSMVgv+Z2VnQwHa0aTsbsgFJbPVyBrlwm9FAv2EdcEQCWqwki4aCBeoODDL1oxPgjrRCvhs3R0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
